const container = document.getElementById("container");
const redParagraph = document.createElement("p");
redParagraph.classList.add("redp");
redParagraph.style.color = "red";
redParagraph.innerText = "Hey, I'm red!";
container.appendChild(redParagraph);
const blueHeader = document.createElement("h3");
blueHeader.style.color = "blue";
container.appendChild(blueHeader);
const pinkDiv = document.createElement("div");
const hInDiv = document.createElement("h1");
const pInDiv = document.createElement("p");
pinkDiv.style.border = "solid black 2px";
pinkDiv.style.background = "pink";
hInDiv.innerText = "I'm in a div!";
pInDiv.innerText = "ME TOO!";
pinkDiv.appendChild(hInDiv);
pinkDiv.appendChild(pInDiv);
container.appendChild(pinkDiv);
